### ISSUE TITLE
[DOC] Data Prepper Getting Started Guide does not work

### ISSUE THREAD

**Issue by Jon-AtAWS** [opensearch-project/documentation-website#1823]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
I was following: https://opensearch.org/docs/1.2/clients/data-prepper/get-started/. I pulled data-prepper:latest, added the simple config, and then ran:

docker run --name data-prepper \
    -v /full/path/to/pipelines.yaml:/usr/share/data-prepper/pipelines.yaml \
    opensearchproject/opensearch-data-prepper:latest

The image here should be data-prepper:latest, instead of opensearch-data-prepper:latest

docker run --name data-prepper \
    -v /full/path/to/pipelines.yaml:/usr/share/data-prepper/pipelines.yaml \
    opensearchproject/data-prepper:latest

Then, I hit this one: 

https://github.com/opensearch-project/data-prepper/issues/1541

And created a local file: data-prepper-config.yaml with the single line

`ssl: false`

Then I ran:

docker run --name data-prepper -v ${PWD}/pipelines.yml:/usr/share/data-prepper/pipelines.yaml \
-v ${PWD}/example_data_prepper_config.yaml:/usr/share/data-prepper/data-prepper-config.yaml \
opensearchproject/data-prepper:1.5.2

Which worked. (I backed up from latest to 1.5.2 in the mean time)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

https://github.com/opensearch-project/data-prepper/issues/1541

**Comment by Jon-AtAWS** [comment]
Here's the error I got from docker run

```
docker run --name data-prepper \
    -v pipelines.yaml:/usr/share/data-prepper/pipelines.yaml \
    opensearchproject/data-prepper:latest
Reading pipelines and data-prepper configuration files from Data Prepper home directory.
/opt/java/openjdk/bin/java
Found openjdk version  of 17.0
2022-11-05T21:42:13,609 [main] INFO  org.opensearch.dataprepper.parser.config.DataPrepperAppConfiguration - Command line args: /usr/share/data-prepper/pipelines,/usr/share/data-prepper/config/data-prepper-config.yaml
2022-11-05T21:42:13,612 [main] INFO  org.opensearch.dataprepper.parser.config.DataPrepperArgs - Using /usr/share/data-prepper/pipelines configuration file
2022-11-05T21:42:13,958 [main] ERROR org.opensearch.dataprepper.parser.PipelineParser - Pipelines configuration file not found at /usr/share/data-prepper/pipelines
2022-11-05T21:42:13,962 [main] WARN  org.springframework.context.support.AbstractApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataPrepperServer' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.0.1.jar!/org/opensearch/dataprepper/pipeline/server/DataPrepperServer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpServer' defined in class path resource [org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.class]: Unsatisfied dependency expressed through method 'httpServer' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'listPipelinesHandler' defined in class path resource [org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.class]: Unsatisfied dependency expressed through method 'listPipelinesHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataPrepper' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.0.1.jar!/org/opensearch/dataprepper/DataPrepper.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opensearch.dataprepper.DataPrepper]: Constructor threw exception; nested exception is org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataPrepperServer' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.0.1.jar!/org/opensearch/dataprepper/pipeline/server/DataPrepperServer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpServer' defined in class path resource [org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.class]: Unsatisfied dependency expressed through method 'httpServer' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'listPipelinesHandler' defined in class path resource [org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.class]: Unsatisfied dependency expressed through method 'listPipelinesHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataPrepper' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.0.1.jar!/org/opensearch/dataprepper/DataPrepper.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opensearch.dataprepper.DataPrepper]: Constructor threw exception; nested exception is org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.opensearch.dataprepper.ContextManager.<init>(ContextManager.java:48)
	at org.opensearch.dataprepper.DataPrepperExecute.main(DataPrepperExecute.java:34)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpServer' defined in class path resource [org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.class]: Unsatisfied dependency expressed through method 'httpServer' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'listPipelinesHandler' defined in class path resource [org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.class]: Unsatisfied dependency expressed through method 'listPipelinesHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataPrepper' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.0.1.jar!/org/opensearch/dataprepper/DataPrepper.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opensearch.dataprepper.DataPrepper]: Constructor threw exception; nested exception is org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 14 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'listPipelinesHandler' defined in class path resource [org/opensearch/dataprepper/pipeline/server/config/DataPrepperServerConfiguration.class]: Unsatisfied dependency expressed through method 'listPipelinesHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataPrepper' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.0.1.jar!/org/opensearch/dataprepper/DataPrepper.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opensearch.dataprepper.DataPrepper]: Constructor threw exception; nested exception is org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 28 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataPrepper' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.0.1.jar!/org/opensearch/dataprepper/DataPrepper.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opensearch.dataprepper.DataPrepper]: Constructor threw exception; nested exception is org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 42 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opensearch.dataprepper.DataPrepper]: Constructor threw exception; nested exception is org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 56 more
Caused by: org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
	at org.opensearch.dataprepper.parser.PipelineParser.mergePipelineConfigurationFiles(PipelineParser.java:137)
	at org.opensearch.dataprepper.parser.PipelineParser.parseConfiguration(PipelineParser.java:84)
	at org.opensearch.dataprepper.DataPrepper.<init>(DataPrepper.java:60)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 58 more
```

**Comment by dlvenable** [comment]
Yes, `data-prepper` is the correct image name.

https://hub.docker.com/r/opensearchproject/data-prepper
