### ISSUE TITLE
Add getting started without docker instructions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/documentation-website#228]
If I download an OpenSearch distribution (not docker), I have to run `opensearch-tar-install.sh`. That's missing from the Getting Started documentation. Add instructions on how to get started next to docker instructions.

If you don't run `opensearch-tar-install.sh` you'll get certificate errors.

```
[2021-10-15T10:48:41,566][INFO ][o.o.n.Node               ] [38f9d370eb4a.ant.amazon.com] version[1.1.0], pid[79891], build[tar/15e9f137622d878b79103df8f82d78d782b686a1/2021-10-15T13:14:16.973135Z], OS[Mac OS X/10.16/x86_64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]
[2021-10-15T10:48:41,569][INFO ][o.o.n.Node               ] [38f9d370eb4a.ant.amazon.com] JVM home [/Users/dblock/source/opensearch-project/opensearch-build/dblock/bundle/opensearch-1.1.0/jdk.app/Contents/Home], using bundled JDK [true]
[2021-10-15T10:48:41,570][INFO ][o.o.n.Node               ] [38f9d370eb4a.ant.amazon.com] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/var/folders/lf/872sgt9n4ld5s20mdj0_5txrds0wb5/T/opensearch-17709225740504744969, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/Users/dblock/source/opensearch-project/opensearch-build/dblock/bundle/opensearch-1.1.0, -Dopensearch.path.conf=/Users/dblock/source/opensearch-project/opensearch-build/dblock/bundle/opensearch-1.1.0/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2021-10-15T10:48:42,909][INFO ][o.o.s.s.t.SSLConfig      ] [38f9d370eb4a.ant.amazon.com] SSL dual mode is disabled
[2021-10-15T10:48:42,909][INFO ][o.o.s.OpenSearchSecurityPlugin] [38f9d370eb4a.ant.amazon.com] OpenSearch Config path is /Users/dblock/source/opensearch-project/opensearch-build/dblock/bundle/opensearch-1.1.0/config
[2021-10-15T10:48:43,212][INFO ][o.o.s.s.DefaultSecurityKeyStore] [38f9d370eb4a.ant.amazon.com] JVM supports TLSv1.3
[2021-10-15T10:48:43,213][INFO ][o.o.s.s.DefaultSecurityKeyStore] [38f9d370eb4a.ant.amazon.com] Config directory is /Users/dblock/source/opensearch-project/opensearch-build/dblock/bundle/opensearch-1.1.0/config/, from there the key- and truststore files are resolved relatively
[2021-10-15T10:48:43,287][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [38f9d370eb4a.ant.amazon.com] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) ~[opensearch-cli-1.1.0.jar:1.1.0]
	at org.opensearch.cli.Command.main(Command.java:103) ~[opensearch-cli-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) ~[opensearch-1.1.0.jar:1.1.0]
Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:736) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:672) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.1.0.jar:1.1.0]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:727) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:672) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.1.0.jar:1.1.0]
	... 6 more
Caused by: org.opensearch.OpenSearchException: plugins.security.ssl.transport.keystore_filepath or plugins.security.ssl.transport.server.pemcert_filepath and plugins.security.ssl.transport.client.pemcert_filepath must be set if transport ssl is requested.
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:422) ~[?:?]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:258) ~[?:?]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:179) ~[?:?]
	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218) ~[?:?]
	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:252) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:727) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:672) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.1.0.jar:1.1.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.1.0.jar:1.1.0]
	... 6 more
uncaught exception in thread [main]
java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
Likely root cause: OpenSearchException[plugins.security.ssl.transport.keystore_filepath or plugins.security.ssl.transport.server.pemcert_filepath and plugins.security.ssl.transport.client.pemcert_filepath must be set if transport ssl is requested.]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:422)
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:258)
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:179)
	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218)
	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:252)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:727)
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:672)
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492)
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181)
	at org.opensearch.node.Node.<init>(Node.java:357)
	at org.opensearch.node.Node.<init>(Node.java:301)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105)
For complete error details, refer to the log at /Users/dblock/source/opensearch-project/opensearch-build/dblock/bundle/opensearch-1.1.0/logs/opensearch.log
```

**Comment by aetter** [comment]
Sure, I've added another header to the main page that has links to the installation sections, specifically calling out the tarball, but Docker is by far our most popular artifact, it's the easiest way to get started, and it runs on every major operating system. We'll soon have at least three other artifacts, so I'm not interested in duplicating all of those install instructions on a getting started page.

**Comment by robbielove** [comment]
The whole installation documentation is terrible!

Honestly installing open search should be a 5 min task but when i go to this page: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/index/
It doesn't actually explain exactly how to install opensearch, instead i fall asleep reading this boring page and wonder why I even came to this page for originally and eventually remember I wanted to know how to install opensearch and still am no closer to the answer.... please sort it out, just cut to the chase and provide steps 1-5 on how to install.

Theres way too much reading between the lines and a lack of detail that leaves more to be desired.

We don't have all day to read all this text and then find out it doesn't apply to us - just shove that in the more info section.
