### ISSUE TITLE
Document rollback (or lack of support thereof)

### ISSUE THREAD

**Issue by balar06** [opensearch-project/documentation-website#436]
Describe the bug
Unable to Rollback OpenSearch 1.2.3 from OpenSearch 1.2.4

Test Case:

- Deploy OpenSearch 1.2.3
- Upgrade OpenSearch 1.2.4
- Rollback to previous version of OpenSearch 1.2.3
- Rollback failed with below error message

```
[2022-03-08T12:01:59.059Z][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [eric-data-search-engine-data-1] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: cannot downgrade a node from version [1.2.4] to version [1.2.3]
at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.2.3.jar:1.2.3]
at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.2.3.jar:1.2.3]
at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.2.3.jar:1.2.3]
Caused by: java.lang.IllegalStateException: cannot downgrade a node from version [1.2.4] to version [1.2.3]
at org.opensearch.env.NodeMetadata.upgradeToCurrentVersion(NodeMetadata.java:105) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:464) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.env.NodeEnvironment.(NodeEnvironment.java:357) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.node.Node.(Node.java:414) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.node.Node.(Node.java:319) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.bootstrap.Bootstrap$5.(Bootstrap.java:242) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.2.3.jar:1.2.3]
at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.2.3.jar:1.2.3]
... 6 more
java.lang.IllegalStateException: cannot downgrade a node from version [1.2.4] to version [1.2.3]
at org.opensearch.env.NodeMetadata.upgradeToCurrentVersion(NodeMetadata.java:105)
at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:464)
at org.opensearch.env.NodeEnvironment.(NodeEnvironment.java:357)
at org.opensearch.node.Node.(Node.java:414)
at org.opensearch.node.Node.(Node.java:319)
at org.opensearch.bootstrap.Bootstrap$5.(Bootstrap.java:242)
at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
at org.opensearch.cli.Command.main(Command.java:101)
at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
```

Expected behavior
Rollback should work.
Is it mentioned in the documentation or release notes?

Host/Environment 

OS: linux

**Comment by dblock** [comment]
This was opened as a bug (https://github.com/opensearch-project/OpenSearch/issues/2405) and became a feature request. Updating this issue to document that rollback is not supported, and how to rollback with snapshots.

**Comment by JeffH-AWS** [comment]
I picked this up.  Just need to identify the best location (or locations) to include this.

**Comment by JeffH-AWS** [comment]
Based on feedback from Naarcha-AWS this would make sense under the FAQ (https://opensearch.org/faq/) and under About OpenSearch (https://opensearch.org/docs/latest/opensearch/index/).

**Comment by JeffH-AWS** [comment]
After reviewing a bit more it made more sense to add the note under the Install landing page (https://opensearch.org/docs/latest/opensearch/install/index/) rather than under About OpenSearch, where the context didn't seem to fit.
