### ISSUE TITLE
[BUG] Infinite redirect loops in docker-compose

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/documentation-website#8542]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** When building the provided development docker file via `docker compose -f docker-compose.dev.yml up`, link checker fails as several links seem to enter infinite redirect loops. This doesn't seem to happen in CI, or when not using the docker compose file. Occasionally the link checker won't fail, but the doc site will actually enter the redirect loop when navigating to one of these pages (it seems to happen with several of the `/index` pages for SQL).
```
$ docker compose -f docker-compose.dev.yml up
...
doc_builder-1  | LinkChecker: [Info] Checking /search-plugins/sql/sql/index/ (./_search-plugins/sql/index.md) 
doc_builder-1  | LinkChecker: [Info] Checking /search-plugins/sql/sql/index/ (./_search-plugins/sql/index.md) 
doc_builder-1  | LinkChecker: [Info] Checking /search-plugins/sql/sql/index/ (./_search-plugins/sql/index.md) 
...
doc_builder-1  | LinkChecker: [Info] Checking /search-plugins/sql/sql/index/ (./_search-plugins/sql/index.md) 
doc_builder-1  | bundler: failed to load command: jekyll (/app/vendor/bundle/ruby/3.2.0/bin/jekyll)
doc_builder-1  | /app/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.4/lib/jekyll/stevenson.rb:7:in `block in initialize': stack level too deep (SystemStackError)
doc_builder-1  |        from /usr/local/lib/ruby/3.2.0/logger.rb:743:in `format_message'
doc_builder-1  |        from /app/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.4/lib/jekyll/stevenson.rb:28:in `add'
doc_builder-1  |        from /usr/local/lib/ruby/3.2.0/logger.rb:695:in `info'
doc_builder-1  |        from /app/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.4/lib/jekyll/log_adapter.rb:148:in `public_send'
doc_builder-1  |        from /app/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.4/lib/jekyll/log_adapter.rb:148:in `write'
doc_builder-1  |        from /app/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.4/lib/jekyll/log_adapter.rb:66:in `info'
doc_builder-1  |        from /app/_plugins/link-checker.rb:264:in `check_internal'
doc_builder-1  |        from /app/_plugins/link-checker.rb:242:in `check'
doc_builder-1  |         ... 7485 levels...
doc_builder-1  |        from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
doc_builder-1  |        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
doc_builder-1  |        from /usr/local/bin/bundle:25:in `load'
doc_builder-1  |        from /usr/local/bin/bundle:25:in `<main>'
doc_builder-1 exited with code 1
```

***Version:** Current mainline, commit f9fb9c1a
 
**What other resources are available?** N/A

**Comment by Naarcha-AWS** [comment]
@Swiddis: I wasn't able to recreate this on my end. Could you show me what your docker.compose file looks like?

**Comment by Swiddis** [comment]
Closing as I haven't been able to repro it lately either, may have been a one-time thing.
